[workspace]
resolver = "3"
members = ['packages/*']
default-members = ["packages/stalkerlike"]

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
