[package]
name = "stalkerlike"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", features = ["vorbis", "wav"] }
bevy_rapier3d = "0.31"
itertools = "0.14"
noise = "0.9"
rand = "0.9"
rusqlite = { version = "0.32", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
image = "0.25"
bevy_egui = "0.38.0"
bevy-inspector-egui = "0.35.0"
bevy_screen_diagnostics = "0.8.1"
bevy_oddio = "0.5.0"
bevy_tweening = "0.14.0"
